### ISSUE TITLE
Teksture

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG39-colorunner#1]
Neophodno je dodati teksture u projekat.

**Comment by djordjeurosevic** [comment]
Dodate su teksture. Kopirao sam images.c i images.h fajl i ucitao 2 teksture, jednu kao sliku za pocetak igre, i jednu za polje na kom se menja boja loptice. Prvobitna ideja je bila da svako polje po kom ide loptica bude u teksturi, ali to bas znacajno uspori igricu pa sam se opredelio za ovo.
