### ISSUE TITLE
Animacija loptice

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG39-colorunner#2]
Unapredjivanje animacije loptice dok prolazi kroz prepreke. Na primer moze menjati oblik i/ili velicinu dok prolazi kroz prepreku iste boje.

**Comment by djordjeurosevic** [comment]
Loptica sada menja velicinu prilikom prolaska kroz prepreku iste boje. 

Dodata je promenljiva GLfloat animacija_prolaska; u fajl logika_igre.c, i prilikom provere na kom se polju loptica nalazi, ukoliko se nalazi na dobro obojenom polju, povecava se taj parametar, ukoliko ne, smanjuje se do nule (ukoliko je bio povecan). A prilikom iscrtavanja loptice u fajlu staza.c, na velicinu loptice se dodaje taj koeficient.
